---
title: "A Review of Inge Druckrey’s Teaching to See"
---

[**September 10th, 2025**]{.underline}

Review by Joseph Martinez

Inge Druckrey was a graphic designer, an abstract artist, a typographer, and above all else, a teacher. She inspired a generation of artists and graphic designers, and the work of her field has left an impression on the likes of Apple Inc. founder and CEO Steve Jobs. Druckrey’s minimalism in her art and designs establishes captivating images, providing inspiration and structure for aspiring data analysts.

One of the most crucial lessons an analyst can take from Druckrey’s work is bold minimalism. Druckrey states that when her student’s work is complete, “There is nothing unnecessary.” As an analyst, noise in visualizations could weaken and dilute the conviction behind the story the analyst’s visualization. Druckrey trained this in her students by creating limitations to the organization of their canvases, much in the way a comic book panelist limits the size and frames of their images to enhance, and not sacrifice, the flow of the comic’s story. In the typography of an alphabet, this is done through the careful contrast of thin and thick strokes and curves versus lines. These contrasts become especially important when addressing the paradox of geographic and optical accuracy. For you see, just because two lines are drawn the same length does not mean the lines will appear the same to the eye. Students must be taught how to adjust their typography and designs to appear as intended to be seen, even if this comes at the expense of true geographic accuracy. However, at the end of the day, it is up to the designer of the typography to express their own work.

For this reason, Druckrey would always allow her students to just throw an idea onto the canvas. Then, Druckrey would “move in carefully and direct” the student towards a final product. Likewise, each analyst must come up with their own style; it may start off as messy, unkempt, and in need of cultivation, but like a signature, it needs the expression of the analyst.

Data analysts turn numbers into stories. Or as Kris Holmes explains, there is a contrast between what we as people wish to see and what we wish to write. The eye “wants everything perfect and rational”; however, our hands write quickly and with passion. Likewise, when we tell stories with data, although our end product must be neat, concise, and legible to others, it will fail to convey if our passion and expression cannot be felt within the design.

Even Steve Jobs, who took calligraphy classes as a dropout at Reed College, recognized the importance of these lessons of passion expressed through bold minimalism. He took these lessons and brought them to the design of the first Macintosh computer, describing these computers as “the first computer with beautiful typography.” The simple and bold design of these first household computers is what opened the door to a brand whose simple logo is in the hands of most Americans to this very day.

There is a quote from Druckrey that has stuck with me the past few nights as I go about editing this rambling of the bold minimalism she inspires. “Graphic design is always visualizing an idea, and it’s definitely about drawing attention. It’s about informing; it's about distance reading. But it’s also about symbolizing something, because like poetry, you have to get the essence of something.” I believe this is not just relevant to data visualization and art but also to how we carry about our lives. The signatures we leave upon this world can be chaotic and uncultivated and later in life refined into grand impact. Regardless of our success in challenging our chaos into order, in our hearts, as we express our lives upon the page of our time on this earth, we are poets.

Source: Severny, A. 2012. Teaching to See. Graphics Press. https://teachingtosee.org/film/TeachingToSee.html
